In [5]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

# Import Data

In [15]:
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])
print(input_data)

[[ 3.  -1.5  3.  -6.4]
 [ 0.   3.  -1.3  4.1]
 [ 1.   2.3 -2.9 -4.3]]


# Scaling

### Standardize

In [71]:
scaler = preprocessing.StandardScaler().fit(input_data)
# scaler = preprocessing.StandardScaler().fit_transform(input_data)
scaler.transform(input_data)

array([[ 1.33630621, -1.39936232,  1.36473933, -0.9258201 ],
       [-1.06904497,  0.87670892, -0.36125453,  1.38873015],
       [-0.26726124,  0.5226534 , -1.0034848 , -0.46291005]])

### MaxMinScaler

In [65]:
data_scaler = preprocessing.MinMaxScaler(feature_range = (0, 1)).fit(input_data)
# data_scaled = data_scaler.fit_transform(input_data)
data_scaled = data_scaler.transform(input_data)
print("\nMin max scaled data = \n", data_scaled)


Min max scaled data = 
 [[ 1.          0.          1.          0.        ]
 [ 0.          1.          0.27118644  1.        ]
 [ 0.33333333  0.84444444  0.          0.2       ]]


### Binarization

In [60]:
threshold = 2.3
data_binarized = preprocessing.Binarizer(threshold = threshold).transform(input_data)
print("input_data = \n %s" % (input_data))
print("\nBinarized data %s = \n %s" % (threshold,data_binarized))

input_data = 
 [[ 3.  -1.5  3.  -6.4]
 [ 0.   3.  -1.3  4.1]
 [ 1.   2.3 -2.9 -4.3]]

Binarized data 2.3 = 
 [[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  0.  0.]]


### Normalize

In [72]:
data_normalized = preprocessing.normalize(input_data, norm  = 'l1')
print("\nL1 normalized data = \n", data_normalized)


L1 normalized data = 
 [[ 0.21582734 -0.10791367  0.21582734 -0.46043165]
 [ 0.          0.35714286 -0.1547619   0.48809524]
 [ 0.0952381   0.21904762 -0.27619048 -0.40952381]]


### One Hot Encoding

In [30]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([  [0, 2, 1, 12], 
               [1, 3, 5, 3], 
               [2, 3, 2, 12], 
               [1, 2, 4, 3]
])
encoded_vector = encoder.transform([[2, 3, 5, 3]]).toarray()
print("\nEncoded vector = \n", encoded_vector)


Encoded vector = 
 [[ 0.  0.  1.  0.  1.  0.  0.  0.  1.  1.  0.]]


### Label Encoding

In [38]:
label_encoder = preprocessing.LabelEncoder()
input_classes = ['suzuki', 'ford', 'suzuki', 'toyota', 'ford', 'bmw']
label_encoder.fit(input_classes)
print("\nClass mapping:")
for i, item in enumerate(label_encoder.classes_):
    print(item, '-->', i)


Class mapping:
bmw --> 0
ford --> 1
suzuki --> 2
toyota --> 3


In [39]:
labels = ['toyota', 'ford', 'suzuki']
encoded_labels = label_encoder.transform(labels)
print("\nLabels =", labels)
print("Encoded labels =", list(encoded_labels))


Labels = ['toyota', 'ford', 'suzuki']
Encoded labels = [3, 1, 2]


In [100]:
x = pd.DataFrame([[1,3,1],[1,3,4],[1,6,5],[1,5,7]],columns=['a','b','c'])
x

a  b  c
0  1  3  1
1  1  3  4
2  1  6  5
3  1  5  7

In [106]:
x.get_dtype_counts()

int64    3
dtype: int64